### ISSUE TITLE
[haxe4rc1] Failed to build due to macro-in-macro error

### ISSUE THREAD

**Issue by kevinresol** [ExternKit/extern-js#4]
At this line:

https://github.com/ExternKit/extern-js/blob/07d04cdb29eb0e8c3880099f13d10085a6c127c6/src/js/extern/ExternBuilder.hx#L35

**Comment by kevinresol** [comment]
@simn do you have an idea how this could trigger macro-in-macro at all?

**Comment by Simn** [comment]
`getDefine` is a macro. You want `Context.definedValue`.

**Comment by kevinresol** [comment]
Aha, didn't realize that. Thanks!
